#!/bin/bash
#title           : git_jumper
#description     : A simple dmenu call to navigate your git repos 
#author		 : Arne Küderle
#date            : 201502
#notes           : Install dmenu to use this script. For the best experience create a hotkey

declare -A gitdic
dirlist=()
while IFS= read -d $'\0' -r file ; do
   dir=$(basename "$(dirname "$file")")
   gitdic["$dir"]="$(dirname "$file")"
   dirlist+="$dir\n"
 done < <(find ~ -type d -name .git -print0)
choice=$(echo -e "$dirlist" | dmenu -fn "-xos4-terminus-medium-r-*-*-20-*")
if [ -n "$choice" ]
    then
        xfce4-terminal --working-directory="${gitdic["$choice"]}"
fi
